
// This file has been generated by the GUI designer. Do not modify.
namespace Scoreboard
{
	public partial class Player
	{
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.TextView textview1;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Button buttonA;
		
		private global::Gtk.Button buttonB;
		
		private global::Gtk.Button buttonBKSpace;
		
		private global::Gtk.Button buttonC;
		
		private global::Gtk.Button buttonD;
		
		private global::Gtk.Button buttonE;
		
		private global::Gtk.Button buttonF;
		
		private global::Gtk.Button buttonG;
		
		private global::Gtk.Button buttonH;
		
		private global::Gtk.Button buttonI;
		
		private global::Gtk.Button buttonJ;
		
		private global::Gtk.Button buttonK;
		
		private global::Gtk.Button buttonkNone;
		
		private global::Gtk.Button buttonL;
		
		private global::Gtk.Button buttonM;
		
		private global::Gtk.Button buttonN;
		
		private global::Gtk.Button buttonO;
		
		private global::Gtk.Button buttonP;
		
		private global::Gtk.Button buttonQ;
		
		private global::Gtk.Button buttonR;
		
		private global::Gtk.Button buttonReturn;
		
		private global::Gtk.Button buttonS;
		
		private global::Gtk.Button buttonSpace;
		
		private global::Gtk.Button buttonT;
		
		private global::Gtk.Button buttonU;
		
		private global::Gtk.Button buttonV;
		
		private global::Gtk.Button buttonW;
		
		private global::Gtk.Button buttonX;
		
		private global::Gtk.Button buttonY;
		
		private global::Gtk.Button buttonZ;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.Button buttonPlay1;
		
		private global::Gtk.Button buttonPlay2;
		
		private global::Gtk.Button buttonPlay3;
		
		private global::Gtk.Button buttonPlay4;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Scoreboard.Player
			this.WidthRequest = 800;
			this.HeightRequest = 450;
			this.Name = "Scoreboard.Player";
			this.Title = global::Mono.Unix.Catalog.GetString ("Player");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Container child Scoreboard.Player.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.Buffer.Text = "Enter player name";
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.Editable = false;
			this.textview1.CursorVisible = false;
			this.vbox6.Add (this.textview1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.textview1]));
			w1.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(10)), true);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.buttonA = new global::Gtk.Button ();
			this.buttonA.CanFocus = true;
			this.buttonA.Name = "buttonA";
			this.buttonA.UseUnderline = true;
			this.buttonA.Label = global::Mono.Unix.Catalog.GetString ("A");
			this.table1.Add (this.buttonA);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonA]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonB = new global::Gtk.Button ();
			this.buttonB.CanFocus = true;
			this.buttonB.Name = "buttonB";
			this.buttonB.UseUnderline = true;
			this.buttonB.Label = global::Mono.Unix.Catalog.GetString ("B");
			this.table1.Add (this.buttonB);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonB]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(4));
			w3.RightAttach = ((uint)(5));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonBKSpace = new global::Gtk.Button ();
			this.buttonBKSpace.CanFocus = true;
			this.buttonBKSpace.Name = "buttonBKSpace";
			this.buttonBKSpace.UseUnderline = true;
			this.buttonBKSpace.Label = global::Mono.Unix.Catalog.GetString ("⇦");
			this.table1.Add (this.buttonBKSpace);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonBKSpace]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(8));
			w4.RightAttach = ((uint)(9));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonC = new global::Gtk.Button ();
			this.buttonC.CanFocus = true;
			this.buttonC.Name = "buttonC";
			this.buttonC.UseUnderline = true;
			this.buttonC.Label = global::Mono.Unix.Catalog.GetString ("C");
			this.table1.Add (this.buttonC);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonC]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(2));
			w5.RightAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonD = new global::Gtk.Button ();
			this.buttonD.CanFocus = true;
			this.buttonD.Name = "buttonD";
			this.buttonD.UseUnderline = true;
			this.buttonD.Label = global::Mono.Unix.Catalog.GetString ("D");
			this.table1.Add (this.buttonD);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonD]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonE = new global::Gtk.Button ();
			this.buttonE.CanFocus = true;
			this.buttonE.Name = "buttonE";
			this.buttonE.UseUnderline = true;
			this.buttonE.Label = global::Mono.Unix.Catalog.GetString ("E");
			this.table1.Add (this.buttonE);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonE]));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonF = new global::Gtk.Button ();
			this.buttonF.CanFocus = true;
			this.buttonF.Name = "buttonF";
			this.buttonF.UseUnderline = true;
			this.buttonF.Label = global::Mono.Unix.Catalog.GetString ("F");
			this.table1.Add (this.buttonF);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonF]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(3));
			w8.RightAttach = ((uint)(4));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonG = new global::Gtk.Button ();
			this.buttonG.CanFocus = true;
			this.buttonG.Name = "buttonG";
			this.buttonG.UseUnderline = true;
			this.buttonG.Label = global::Mono.Unix.Catalog.GetString ("G");
			this.table1.Add (this.buttonG);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonG]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(4));
			w9.RightAttach = ((uint)(5));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonH = new global::Gtk.Button ();
			this.buttonH.CanFocus = true;
			this.buttonH.Name = "buttonH";
			this.buttonH.UseUnderline = true;
			this.buttonH.Label = global::Mono.Unix.Catalog.GetString ("H");
			this.table1.Add (this.buttonH);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonH]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(5));
			w10.RightAttach = ((uint)(6));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonI = new global::Gtk.Button ();
			this.buttonI.CanFocus = true;
			this.buttonI.Name = "buttonI";
			this.buttonI.UseUnderline = true;
			this.buttonI.Label = global::Mono.Unix.Catalog.GetString ("I");
			this.table1.Add (this.buttonI);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonI]));
			w11.LeftAttach = ((uint)(7));
			w11.RightAttach = ((uint)(8));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonJ = new global::Gtk.Button ();
			this.buttonJ.CanFocus = true;
			this.buttonJ.Name = "buttonJ";
			this.buttonJ.UseUnderline = true;
			this.buttonJ.Label = global::Mono.Unix.Catalog.GetString ("J");
			this.table1.Add (this.buttonJ);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonJ]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(6));
			w12.RightAttach = ((uint)(7));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonK = new global::Gtk.Button ();
			this.buttonK.CanFocus = true;
			this.buttonK.Name = "buttonK";
			this.buttonK.UseUnderline = true;
			this.buttonK.Label = global::Mono.Unix.Catalog.GetString ("K");
			this.table1.Add (this.buttonK);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonK]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(7));
			w13.RightAttach = ((uint)(8));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonkNone = new global::Gtk.Button ();
			this.buttonkNone.CanFocus = true;
			this.buttonkNone.Name = "buttonkNone";
			this.buttonkNone.UseUnderline = true;
			this.buttonkNone.Label = global::Mono.Unix.Catalog.GetString ("NONE");
			this.table1.Add (this.buttonkNone);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonkNone]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.LeftAttach = ((uint)(9));
			w14.RightAttach = ((uint)(10));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonL = new global::Gtk.Button ();
			this.buttonL.CanFocus = true;
			this.buttonL.Name = "buttonL";
			this.buttonL.UseUnderline = true;
			this.buttonL.Label = global::Mono.Unix.Catalog.GetString ("L");
			this.table1.Add (this.buttonL);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonL]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(8));
			w15.RightAttach = ((uint)(9));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonM = new global::Gtk.Button ();
			this.buttonM.CanFocus = true;
			this.buttonM.Name = "buttonM";
			this.buttonM.UseUnderline = true;
			this.buttonM.Label = global::Mono.Unix.Catalog.GetString ("M");
			this.table1.Add (this.buttonM);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonM]));
			w16.TopAttach = ((uint)(2));
			w16.BottomAttach = ((uint)(3));
			w16.LeftAttach = ((uint)(6));
			w16.RightAttach = ((uint)(7));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonN = new global::Gtk.Button ();
			this.buttonN.CanFocus = true;
			this.buttonN.Name = "buttonN";
			this.buttonN.UseUnderline = true;
			this.buttonN.Label = global::Mono.Unix.Catalog.GetString ("N");
			this.table1.Add (this.buttonN);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonN]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.LeftAttach = ((uint)(5));
			w17.RightAttach = ((uint)(6));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonO = new global::Gtk.Button ();
			this.buttonO.CanFocus = true;
			this.buttonO.Name = "buttonO";
			this.buttonO.UseUnderline = true;
			this.buttonO.Label = global::Mono.Unix.Catalog.GetString ("O");
			this.table1.Add (this.buttonO);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonO]));
			w18.LeftAttach = ((uint)(8));
			w18.RightAttach = ((uint)(9));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonP = new global::Gtk.Button ();
			this.buttonP.CanFocus = true;
			this.buttonP.Name = "buttonP";
			this.buttonP.UseUnderline = true;
			this.buttonP.Label = global::Mono.Unix.Catalog.GetString ("P");
			this.table1.Add (this.buttonP);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonP]));
			w19.LeftAttach = ((uint)(9));
			w19.RightAttach = ((uint)(10));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonQ = new global::Gtk.Button ();
			this.buttonQ.CanFocus = true;
			this.buttonQ.Name = "buttonQ";
			this.buttonQ.UseUnderline = true;
			this.buttonQ.Label = global::Mono.Unix.Catalog.GetString ("Q");
			this.table1.Add (this.buttonQ);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonQ]));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonR = new global::Gtk.Button ();
			this.buttonR.CanFocus = true;
			this.buttonR.Name = "buttonR";
			this.buttonR.UseUnderline = true;
			this.buttonR.Label = global::Mono.Unix.Catalog.GetString ("R");
			this.table1.Add (this.buttonR);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonR]));
			w21.LeftAttach = ((uint)(3));
			w21.RightAttach = ((uint)(4));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonReturn = new global::Gtk.Button ();
			this.buttonReturn.CanFocus = true;
			this.buttonReturn.Name = "buttonReturn";
			this.buttonReturn.UseUnderline = true;
			this.buttonReturn.Label = global::Mono.Unix.Catalog.GetString ("↲");
			this.table1.Add (this.buttonReturn);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonReturn]));
			w22.TopAttach = ((uint)(1));
			w22.BottomAttach = ((uint)(2));
			w22.LeftAttach = ((uint)(9));
			w22.RightAttach = ((uint)(10));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonS = new global::Gtk.Button ();
			this.buttonS.CanFocus = true;
			this.buttonS.Name = "buttonS";
			this.buttonS.UseUnderline = true;
			this.buttonS.Label = global::Mono.Unix.Catalog.GetString ("S");
			this.table1.Add (this.buttonS);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonS]));
			w23.TopAttach = ((uint)(1));
			w23.BottomAttach = ((uint)(2));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(2));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonSpace = new global::Gtk.Button ();
			this.buttonSpace.CanFocus = true;
			this.buttonSpace.Name = "buttonSpace";
			this.buttonSpace.UseUnderline = true;
			this.buttonSpace.Label = global::Mono.Unix.Catalog.GetString ("˽");
			this.table1.Add (this.buttonSpace);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonSpace]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.LeftAttach = ((uint)(7));
			w24.RightAttach = ((uint)(8));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonT = new global::Gtk.Button ();
			this.buttonT.CanFocus = true;
			this.buttonT.Name = "buttonT";
			this.buttonT.UseUnderline = true;
			this.buttonT.Label = global::Mono.Unix.Catalog.GetString ("T");
			this.table1.Add (this.buttonT);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonT]));
			w25.LeftAttach = ((uint)(4));
			w25.RightAttach = ((uint)(5));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonU = new global::Gtk.Button ();
			this.buttonU.CanFocus = true;
			this.buttonU.Name = "buttonU";
			this.buttonU.UseUnderline = true;
			this.buttonU.Label = global::Mono.Unix.Catalog.GetString ("U");
			this.table1.Add (this.buttonU);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonU]));
			w26.LeftAttach = ((uint)(6));
			w26.RightAttach = ((uint)(7));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonV = new global::Gtk.Button ();
			this.buttonV.CanFocus = true;
			this.buttonV.Name = "buttonV";
			this.buttonV.UseUnderline = true;
			this.buttonV.Label = global::Mono.Unix.Catalog.GetString ("V");
			this.table1.Add (this.buttonV);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonV]));
			w27.TopAttach = ((uint)(2));
			w27.BottomAttach = ((uint)(3));
			w27.LeftAttach = ((uint)(3));
			w27.RightAttach = ((uint)(4));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonW = new global::Gtk.Button ();
			this.buttonW.CanFocus = true;
			this.buttonW.Name = "buttonW";
			this.buttonW.UseUnderline = true;
			this.buttonW.Label = global::Mono.Unix.Catalog.GetString ("W");
			this.table1.Add (this.buttonW);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonW]));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonX = new global::Gtk.Button ();
			this.buttonX.CanFocus = true;
			this.buttonX.Name = "buttonX";
			this.buttonX.UseUnderline = true;
			this.buttonX.Label = global::Mono.Unix.Catalog.GetString ("X");
			this.table1.Add (this.buttonX);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonX]));
			w29.TopAttach = ((uint)(2));
			w29.BottomAttach = ((uint)(3));
			w29.LeftAttach = ((uint)(1));
			w29.RightAttach = ((uint)(2));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonY = new global::Gtk.Button ();
			this.buttonY.CanFocus = true;
			this.buttonY.Name = "buttonY";
			this.buttonY.UseUnderline = true;
			this.buttonY.Label = global::Mono.Unix.Catalog.GetString ("Y");
			this.table1.Add (this.buttonY);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonY]));
			w30.LeftAttach = ((uint)(5));
			w30.RightAttach = ((uint)(6));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonZ = new global::Gtk.Button ();
			this.buttonZ.CanFocus = true;
			this.buttonZ.Name = "buttonZ";
			this.buttonZ.UseUnderline = true;
			this.buttonZ.Label = global::Mono.Unix.Catalog.GetString ("Z");
			this.table1.Add (this.buttonZ);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonZ]));
			w31.TopAttach = ((uint)(2));
			w31.BottomAttach = ((uint)(3));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox6.Add (this.table1);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.table1]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(1)), ((uint)(4)), true);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.buttonPlay1 = new global::Gtk.Button ();
			this.buttonPlay1.CanFocus = true;
			this.buttonPlay1.Name = "buttonPlay1";
			this.buttonPlay1.FocusOnClick = false;
			this.buttonPlay1.Relief = ((global::Gtk.ReliefStyle)(2));
			this.buttonPlay1.Label = global::Mono.Unix.Catalog.GetString ("Player 1");
			this.table2.Add (this.buttonPlay1);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table2 [this.buttonPlay1]));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.buttonPlay2 = new global::Gtk.Button ();
			this.buttonPlay2.CanFocus = true;
			this.buttonPlay2.Name = "buttonPlay2";
			this.buttonPlay2.UseUnderline = true;
			this.buttonPlay2.FocusOnClick = false;
			this.buttonPlay2.Label = global::Mono.Unix.Catalog.GetString ("Player 2");
			this.table2.Add (this.buttonPlay2);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table2 [this.buttonPlay2]));
			w34.LeftAttach = ((uint)(1));
			w34.RightAttach = ((uint)(2));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.buttonPlay3 = new global::Gtk.Button ();
			this.buttonPlay3.CanFocus = true;
			this.buttonPlay3.Name = "buttonPlay3";
			this.buttonPlay3.UseUnderline = true;
			this.buttonPlay3.FocusOnClick = false;
			this.buttonPlay3.Label = global::Mono.Unix.Catalog.GetString ("Player 3");
			this.table2.Add (this.buttonPlay3);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table2 [this.buttonPlay3]));
			w35.LeftAttach = ((uint)(2));
			w35.RightAttach = ((uint)(3));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.buttonPlay4 = new global::Gtk.Button ();
			this.buttonPlay4.CanFocus = true;
			this.buttonPlay4.Name = "buttonPlay4";
			this.buttonPlay4.UseUnderline = true;
			this.buttonPlay4.FocusOnClick = false;
			this.buttonPlay4.Label = global::Mono.Unix.Catalog.GetString ("Player 4");
			this.table2.Add (this.buttonPlay4);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table2 [this.buttonPlay4]));
			w36.LeftAttach = ((uint)(3));
			w36.RightAttach = ((uint)(4));
			w36.XOptions = ((global::Gtk.AttachOptions)(4));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox6.Add (this.table2);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.table2]));
			w37.Position = 2;
			w37.Expand = false;
			w37.Fill = false;
			this.Add (this.vbox6);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1164;
			this.DefaultHeight = 480;
			this.Show ();
			this.buttonZ.Clicked += new global::System.EventHandler (this.OnButtonZClicked);
			this.buttonY.Clicked += new global::System.EventHandler (this.OnButtonYClicked);
			this.buttonX.Clicked += new global::System.EventHandler (this.OnButtonXClicked);
			this.buttonW.Clicked += new global::System.EventHandler (this.OnButtonWClicked);
			this.buttonV.Clicked += new global::System.EventHandler (this.OnButtonVClicked);
			this.buttonU.Clicked += new global::System.EventHandler (this.OnButtonUClicked);
			this.buttonT.Clicked += new global::System.EventHandler (this.OnButtonTClicked);
			this.buttonSpace.Clicked += new global::System.EventHandler (this.OnButtonSpaceClicked);
			this.buttonS.Clicked += new global::System.EventHandler (this.OnButtonSClicked);
			this.buttonReturn.Clicked += new global::System.EventHandler (this.OnButtonReturnClicked);
			this.buttonR.Clicked += new global::System.EventHandler (this.OnButtonRClicked);
			this.buttonQ.Clicked += new global::System.EventHandler (this.OnButtonQClicked);
			this.buttonP.Clicked += new global::System.EventHandler (this.OnButtonPClicked);
			this.buttonO.Clicked += new global::System.EventHandler (this.OnButtonOClicked);
			this.buttonN.Clicked += new global::System.EventHandler (this.OnButtonNClicked);
			this.buttonM.Clicked += new global::System.EventHandler (this.OnButtonMClicked);
			this.buttonL.Clicked += new global::System.EventHandler (this.OnButtonLClicked);
			this.buttonkNone.Clicked += new global::System.EventHandler (this.OnButtonkNoneClicked);
			this.buttonK.Clicked += new global::System.EventHandler (this.OnButtonKClicked);
			this.buttonJ.Clicked += new global::System.EventHandler (this.OnButtonJClicked);
			this.buttonI.Clicked += new global::System.EventHandler (this.OnButtonIClicked);
			this.buttonH.Clicked += new global::System.EventHandler (this.OnButtonHClicked);
			this.buttonG.Clicked += new global::System.EventHandler (this.OnButtonGClicked);
			this.buttonF.Clicked += new global::System.EventHandler (this.OnButtonFClicked);
			this.buttonE.Clicked += new global::System.EventHandler (this.OnButtonEClicked);
			this.buttonD.Clicked += new global::System.EventHandler (this.OnButtonDClicked);
			this.buttonC.Clicked += new global::System.EventHandler (this.OnButtonCClicked);
			this.buttonBKSpace.Clicked += new global::System.EventHandler (this.OnButtonBKSpaceClicked);
			this.buttonB.Clicked += new global::System.EventHandler (this.OnButtonBClicked);
			this.buttonA.Clicked += new global::System.EventHandler (this.OnButtonAClicked);
			this.buttonPlay4.Clicked += new global::System.EventHandler (this.OnButtonPlay4Clicked);
			this.buttonPlay3.Clicked += new global::System.EventHandler (this.OnButtonPlay3Clicked);
			this.buttonPlay2.Clicked += new global::System.EventHandler (this.OnButtonPlay2Clicked);
			this.buttonPlay1.Clicked += new global::System.EventHandler (this.OnButtonPlay1Clicked);
		}
	}
}
